### ISSUE TITLE
Question about pulling different state slices together

### ISSUE THREAD

**Issue by jbalboni** [raisemarketplace/redux-loop#10]
This was mentioned offhand in https://github.com/raisemarketplace/redux-loop/issues/4#issuecomment-173378176, but I was curious how I could get state information from outside the slice the reducer is operating on, if I switched to using redux-loop. 

Currently, I would use redux-thunk and the getState function that's passed to the function you return from an action creator. So, for example, I have an action creator now that looks sort of like:

    function actionCreator(id) {
       return thunk(dispatch, getState) {
           SomeApi.get(id).then(function(results) {
               dispatch({
                   type: 'ACTION',
                   someOtherInfo: getState().path.to.info,
                   results: results
               })
          }
    }

I understand how I'd move the api call to an Effect, but I'm not sure how I'd replicate getState(). I suppose I could have some magic properties in the action object that were replaced with the state by middleware. I'm curious if you have any thoughts or patterns for this situation.

Kudos on this library, it looks so much cleaner and easier to test than using redux-thunk.

**Comment by lukewestby** [comment]
Thanks for your question! This is a good one and something that should be highlighted in the docs. So one option is to do it the Elm way, and pass that info from another area in your state down through the view layer via `props` on your components. From there you can pass `state.path.to.info` into your action creator as an argument. Granted, this can be pretty tedious if you've got a lot of nesting happening. So the other recommendation, and one that we've agreed on at Raise as well, is to continue to use `redux-thunk` to pull in different parts of your state and only move the API call into an Effect. Your thunk action creator might look like this:

```javascript
function apiGetStart(id) {
  return (dispatch, getState) => {
    dispatch({
      type: 'API_GET_START',
      id: id,
      someOtherInfo: getState().path.to.info,
    });
  };
}
```

This library wasn't intended to remove `redux-thunk` from the picture entirely, just the async aspect of it and async action creators in general.

If you've got any more questions feel free to open more issues! Or if you prefer StackOverflow we check the `redux-loop` tag several times a day as well.

**Comment by yelouafi** [comment]
How about having a separate reducer for those kind of effects. The reducer wont return any state but just pull out the required info from the state atom and return one or more action effects to be handled by *normal* reducers.

BTW nice work @lukewestby

**Comment by lukewestby** [comment]
I think the conceptual buy-in of this library is that effects should be colocated with the parts of the state to which they are most pertinent. If the shape of the state is such that it would be easier to manage side-effects separately from state transitions I think folks would be much better served with [redux-saga](https://github.com/yelouafi/redux-saga).

---

> BTW nice work @lukewestby
Thanks @yelouafi! That means a lot :smile:

**Comment by jbalboni** [comment]
Thanks @lukewestby!
