### ISSUE TITLE
Add ability to lift effects

### ISSUE THREAD

**Issue by lukewestby** [raisemarketplace/redux-loop#16]
redux-loop notably lacks the functionality provided by `Effects.map` in elm-effects. There's an important difference between Elm and redux-loop here, in that functions are not comparable in Elm but we can still do reference equality in JavaScript, so adding this functionality should _not_ break `deepEquals` comparisons. Also, the ability to do arbitrary mapping might lead folks to try to chain transformations together using anonymous functions, which they won't be able to test easily.

In my Elm experience the only use I've found for `Effects.map` is to map nested actions onto a dedicated higher-order action for the parent's update function.

With all of this in mind, I want to limit the scope of any mapping functionality in redux-loop to just lifting actions into higher-order actions, at least for now. This should take the form of a new effect type in redux-loop called `lift`.

As of redux-loop 1.0.4, all effects promises resolve an array of actions regardless of whether they are guaranteed to produce 1 or 0. This should make it easy to store a lower effect and a reference to an action creator to lift with, and just map over the lower actions with it once they've resolved. Ideally, we should have some sanity checks in place to throw if the result of lifting is not also an action, but I want to track adding sanity checks as a different story. So feel free to add them, or not.

**Comment by lukewestby** [comment]
cc @jarvisaoieong, i saw that you were working on `map` functionality in your fork

**Comment by jarvisaoieong** [comment]
I'd like to help. I've do some experiment to port the elm architecture examples to redux with the redux-loop. I also fork the redux-logger to support async action logging with the power of redux-loop. 

I will show these examples for discussing.

**Comment by jarvisaoieong** [comment]
Oked, let's check it out.

source code: https://github.com/jarvisaoieong/redux-architecture
live demo: http://jarvisaoieong.github.io/redux-architecture/

In the live demo, please open the console to see some log
![b88cb411-6c27-4f00-86aa-27ef7f7168bc](https://cloud.githubusercontent.com/assets/195635/13028689/503e494e-d2b1-11e5-858e-23a78f17b6cc.png)

I will update the README for more information later.

**Comment by lukewestby** [comment]
@jarvisaoieong this is fantastic! I love the logger integration, super helpful for tracing action paths.

I think your implementation of `Effects.map` is exactly what we would want for `Effects.lift`. Do you want to rename and submit a PR?

**Comment by jarvisaoieong** [comment]
Nice you like it. I will submit a PR today.

**Comment by lukewestby** [comment]
published v1.1.0!
