### ISSUE TITLE
Combine Effects.promise and Effects.constant to Effects.call

### ISSUE THREAD

**Issue by jarvisaoieong** [raisemarketplace/redux-loop#20]
if the Effects.promise internal resolve implementation add a safe promise wrapper, e.g.

```javascript
switch (effect.type) {
    case effectTypes.PROMISE:
      return Promise.resolve(effect.factory(...effect.args)).then((action) => [action]);
``` 

then the Effects.constant call 

```js
Effects.constant(someAction(1))
```

can change to

```js
Effects.promise(someAction, 1)
```

and I propose rename it to Effects.call or something other.

In user land, we don't need to care whether it is a task or simple action.

**Comment by lukewestby** [comment]
I definitely see where you're coming from, but I don't agree that users don't need to care whether the effect is as task or a simple action for a couple reasons.

- Separate names allow the different functions to be self-documenting and reduce the amount of implicit behavior the user needs to manage in their mind
- Allows us to do sanity checks (#17) to verify that the user has passed the correct kind of value
- Leaves open the ability to add additional effects types, like `tick` from elm-effects or `callback` to accept node-style callbacks, without overloading a general term like "call"

In general I want to avoid overloading and have every function expect one kind of data as much as possible, whether it's in arguments or the return value.

**Comment by jarvisaoieong** [comment]
Make sense! Thank you for detailed explanation.

**Comment by lukewestby** [comment]
No problem! And thank you for your input and suggestions! Your contributions this week have been great, we really appreciate them. Okay to close this issue?

**Comment by jarvisaoieong** [comment]
It's my pleasure. I close it.
