### ISSUE TITLE
Add second param in Effects.batch

### ISSUE THREAD

**Issue by jarvisaoieong** [raisemarketplace/redux-loop#22]
Use case:

```js
const initReducer = (state = {isloading: true}, action) => {
  if (action.type === INIT) {
    return loop({
      ...state,
      isloading: true,
    },
      Effects.batch([
        Effects.promise(someAsyncAction),
        Effects.promise(anotherAsyncAction),
      ],
        Effects.constant(inited())
      )
    );
  }

  if (action.type === INITED) {
    return loop({
      ...state,
      isloading: false,
    },
      Effects.none()
    );
  }

  return loop(state, Effects.none());
}
```

If it make sense, i am willing to submit a PR.

**Comment by lukewestby** [comment]
What would be different about the execution of the effect in the second parameter vs. those in the first?

**Comment by jarvisaoieong** [comment]
the second param effect will execute when the first param effect finished

**Comment by jarvisaoieong** [comment]
maybe the second param can called afterBatchFinishedEffect :)

**Comment by lukewestby** [comment]
So, with `Effects.batch` none of the actions will be dispatched until all of the effects are finished. If you pass `Effects.constant(inited())` as the third element of the array it will be dispatched immediately after the first 2 are dispatched. Do you think this is too implicit for what is intended?

**Comment by jarvisaoieong** [comment]
the effectToPromise implementation maybe like this

```js
case effectTypes.BATCH:
  return Promise.all(effect.effects.map(effectToPromise))
    .then((actions) => 
      effect.afterBatchFinishedEffect
        ? effectToPromise(effect.afterBatchFinishedEffect).then((action) => [...actions, action])
        : actions
    ) 
    .then(flatten);
```

**Comment by jarvisaoieong** [comment]
> pass Effects.constant(inited()) as the third element of the array

good point!!!

**Comment by jarvisaoieong** [comment]
Oh, I think it will solve the problem. closed

**Comment by lukewestby** [comment]
In any case, I probably didn't document that feature of `Effects.batch` clearly enough. Thank you again for your suggestion! Keep'em coming if you've got more 😀
