### ISSUE TITLE
Suggestion: Dont use Symbol

### ISSUE THREAD

**Issue by jarvisaoieong** [raisemarketplace/redux-loop#31]
In mobile, the browser compatibility of Symbol is poor. 
We dont intend to use polyfill in the mobile env to increase the file size.

P.S. I have used half of day to debug in IOS env because of the Symbol. It's very difficult to find a tool to inspect the iOS device.

**Comment by lukewestby** [comment]
I'm not sure I want to change this right now. Symbols work really well for the use case here of identifying which objects have been created by `Effects`. This is going to be increasingly important as we start to add more helpful error messages when a function expects an effect and was given something else.

FWIW, [iOS 9 supports Symbols](http://kangax.github.io/compat-table/es6/#ios9), and if file size is a concern for <= iOS 8 you can write a Symbol polyfill complete enough to use with redux-loop in less than 50 lines of code. You don't need to import all of `babel-polyfill` for it to work.

**Comment by jarvisaoieong** [comment]
I know the benefit of Symbol. Maybe we should write down this caution in the doc.

**Comment by lukewestby** [comment]
Agreed! I'll mention the Promise requirement for older browsers as well.

**Comment by lukewestby** [comment]
Added a note to the README, thank you!
