### ISSUE TITLE
Suggestion: Add Effects.generator

### ISSUE THREAD

**Issue by tarjei** [raisemarketplace/redux-loop#32]
Hi, after using `redux-saga`I have fallen in love with JS generator functions. Would it be possible to have a generator function effect that runs the generator function until it is done?

**Comment by lukewestby** [comment]
I'm definitely interested in seeing how this could play out, would you mind sharing an example of what such a generator might look like?

**Comment by lukewestby** [comment]
Closing until we hear back

[CONTRIBUTING.md](https://github.com/raisemarketplace/redux-loop/blob/master/CONTRIBUTING.md#issues)

**Comment by tarjei** [comment]
I'm sorry for not getting back to you @lukewestby , but a generator might look like this:

```javascript
function * postToServerAction() {
     ...
     const result = someAjaxLib("GET", "/url")
     yield ajaxResultAction(result)
}
```
One could also think that a generator yielded multiple results:
```javascript
function * postToServerAction() {
     for (i < 2; i++) {
     const result = someAjaxLib("GET", "/url")
     yield  myAction(result)
    }
}
```
Where each result would be an action to be handled by the store. 

Is this what you're looking for ?

Also, note that a generator function returns an iterator with a special done attribute that you can check.

**Comment by lukewestby** [comment]
If you'd just like to use generators to abstract async behavior in an `async/await` like manor I would suggest bringing in something like [co](https://github.com/tj/co) and using that in conjunction with `Effects.promise`. Regarding yielding multiple actions, this is something redux-saga is really good at and built to do and you can totally use it together with redux-loop without issue, even though saga and loop are often presented as mutually exclusive solutions to one uniform problem.

I want to avoid as much as I can introducing higher-order things like long-running generators where one action can result in an arbitrary number of actions over some period of time. One action can cause as many actions in the future as you want, but they should all be scheduled at the same time via `Effects.batch()`

**Comment by tarjei** [comment]
OK, thanks for the input :)

2016-04-19 23:19 GMT+02:00 Luke Westby <notifications@github.com>:

> If you'd just like to use generators to abstract async behavior in an
> async/await like manor I would suggest bringing in something like co
> <https://github.com/tj/co> and using that in conjunction with
> Effects.promise. Regarding yielding multiple actions, this is something
> redux-saga is really good at and built to do and you can totally use it
> together with redux-loop without issue, even though saga and loop are often
> presented as mutually exclusive solutions to one uniform problem.
>
> I want to avoid as much as I can introducing higher-order things like
> long-running generators where one action can result in an arbitrary number
> of actions over some period of time. One action can cause as many actions
> in the future as you want, but they should all be scheduled at the same
> time via Effects.batch()
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/raisemarketplace/redux-loop/issues/32#issuecomment-212134476>
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413
