### ISSUE TITLE
redux-loop 2.1.0 breaks redux-form

### ISSUE THREAD

**Issue by tarjei** [raisemarketplace/redux-loop#44]
Hi, I just upgraded to 2.1.0 to get access to Effects.call, when I experienced this. 

I'm using http://redux-form.com/4.2.0 and this works quite nicely with redux-loop 2.0.0.

When I upgrade to 2.1 things stop working.

That is, if I change a field, the action is dispatched (as seen in DevTools), but the the new state is not propagated to React - i.e. the properties in the form are not updated.

I have tried to understand what is breaking here for a few hours now, but I'm a bit stumped to be honest and would love to get some tips to what this could be / where I should start looking for clues to what is failing. 

Kind regards,
Tarjei

**Comment by lukewestby** [comment]
Can you share a minimal reducer and store configuration where you can see this problem occurring? There weren't intended to be any breaking changes between the two versions but I might have messed something up.

**Comment by tarjei** [comment]
Hi, yes I'll try to look into it :)
