### ISSUE TITLE
Effect.promise executed twice.

### ISSUE THREAD

**Issue by tarjei** [raisemarketplace/redux-loop#45]
Hi, I got two reducers (out of 7) that return effects. 

This is with redux-loop 2.0.0.

Now, the simplest of the two is doing something very odd. When I return a promise, the promiseFactory function is executed twice(!):

```javascript
import { loop, Effects } from 'redux-loop'

import { createAction, handleActions } from 'redux-actions'

export const GROWL_MESSAGE = 'growl'
export const GROWL_CLEAR = 'growl-clear'

export const growlAction = createAction(GROWL_MESSAGE, function(message, type = 'info', timeout = 6000) {
  return { message, type, timeout }
})

export const clearGrowlAction = createAction(GROWL_CLEAR)

export function executeTimeout(growl) {
  console.log("executeTimeout")
  return new Promise(function(resolve, reject) {
    setTimeout(
      function() {
        resolve(clearGrowlAction(growl))
      },
      growl.timeout
    )
  }).catch(function(e) {
    console.error(e)
  })
}

export const growlReducer = function(state = { growls: []}, { type, payload }) {
  
  if (type === GROWL_MESSAGE) {
    const growl = {
      message: payload.message,
      type: payload.type,
      timeout: payload.timeout,
    }
    state.growls = [growl, ...state.growls]
    return loop(state, Effects.promise(executeTimeout, growl))
  } else if (type === GROWL_CLEAR) {
    state.growls = state.growls.filter((growl) => {
      return growl !== payload
    })
  }
  return state
}
export default growlReducer
```

Now, when growlAction() is dispatched, the reducer is executed once, but then executeTimeout is called twice with the same arguments.

I'm a bit stumped at this one. Any ideas?

When I add a console.log to `install( -> dispatch() ) ` in  `install.js` like this: 
```javascript
function dispatch(action) {
        var dispatchedAction = store.dispatch(action);
        console.log("DISPATCH " + action.type, store.getState())
        var effect = (0, _loop.getEffect)(store.getState());
        return runEffect(action, effect).then(function () {});
      }

```
I get that the action type is different (once it is GROWL_CLEAR, then it is an action in another reducer) in the two occasions, but that the effect for the executeTimeout.

Any ideas what is happening here?

I'm a bit stumped

**Comment by tarjei** [comment]
Hi Again, I thought I'd throw in the configureStore function for good measure :)

```js

import { applyMiddleware, compose, createStore } from 'redux'
import { routerMiddleware } from 'react-router-redux'
import rootReducer from './rootReducer'
import { install } from 'redux-loop'

export default function configureStore (initialState = {
  db: {
    entities: {},
    queryResults: {}
  }
}, history) {
  
  let middleware = compose(install(), applyMiddleware(routerMiddleware(history)))

  if (__DEBUG__) {
    const devTools = window.devToolsExtension
      ? window.devToolsExtension()
      : require('containers/DevTools').default.instrument()
    middleware = compose(middleware, devTools)
  }

  // console.log('initialState', initialState)

  const store = middleware(createStore)(rootReducer, initialState)

  if (module.hot) {
    module.hot.accept('./rootReducer', () => {
      const nextRootReducer = require('./rootReducer').default

      store.replaceReducer(nextRootReducer)
    })
  }
  return store
}
```

**Comment by lukewestby** [comment]
@tarjei that's a serious issue! I'll start looking into it this weekend at the latest. Thank you so much for including all of this context in your issue, exemplary! I'll let you know if I need any more information. And if you (or anyone else) figures it out before then please feel free to submit a PR as always.

**Comment by tarjei** [comment]
Thanks @lukewestby I'm a bit stumped at what can be happening here. I tried rewriting all my reducers to return objects, but that did not change anything. Anyhow, at least that possibility is excluded.

**Comment by tarjei** [comment]
I have kind of an intuition that what is happening is that the promise is not removed from the state after it has been executed in runEffects() but I do not understand enough internals to be sure.

**Comment by lukewestby** [comment]
@tarjei i went with your intuition and added a change to remove the effect from the store entirely and track it separately. i've been meaning to do this for some time but i think it'll help here as well. can you install 2.1.1 and see if this fixes things? if not i'll do some more detailed investigation 😄
