### ISSUE TITLE
Default mutator don't create new object

### ISSUE THREAD

**Issue by Egor-Sapronov** [raisemarketplace/redux-loop#47]
I use plain objects for reducers and have problem with this, because state mutate but link for the object don't change

Fix in this [pr](https://github.com/raisemarketplace/redux-loop/pull/46)

**Comment by lukewestby** [comment]
@Egor-Sapronov thanks for your contribution! Before I merge your PR can you give an example of the issues this is currently causing in your application?

**Comment by Egor-Sapronov** [comment]
@lukewestby it happens when i use nested reducers like
```
combineReducers({someNestedReducer})
``` 

There is full example of this issue
```
function counter(state = { value: 0 }, action) {
    switch (action.type) {
        case 'INCREMENT':
            return {
                value: state.value + 1
            };
        default:
            return state;
    }
}

const store = createStore(combineReducers({counter}), install());

function select(state) {
    return {
        value: state.counter.value
    };
}

class App extends Component {
    handleClick = () => {
        this.props.dispatch({
            type: 'INCREMENT'
        });
    }

    render() {
        const { value } = this.props;
        return (
            <div>
                <p>Value: { value }</p>
                <button onClick={ this.handleClick }>Click</button>
            </div>
        );
    }
}

const Root = connect(select)(App);
```

State was changes and subscribe on the store fired, but link to the store doesn't changed. Function connect from react-redux has pure render option by default, so if state not changed it not rerender the wrapped component

**Comment by lukewestby** [comment]
Gotcha! Sounds good. I'm going to release tomorrow so I'll merge it then. Thanks!

**Comment by Egor-Sapronov** [comment]
Thanks you for working on this library!

**Comment by lukewestby** [comment]
It's my pleasure! Really, most of the work on it comes from the community. Y'all make my job easy 😄
