### ISSUE TITLE
Integration tests with redux-loop?

### ISSUE THREAD

**Issue by aksonov** [raisemarketplace/redux-loop#48]
I'm trying to run mock redux store from my unit tests according to:
https://github.com/reactjs/redux/blob/master/docs/recipes/WritingTests.md

It works well for redux-thunk as well as redux-saga, because they are 'middleware' that could be set inside 'mock' redux store, but i can't figure out how to do it with redux-loop with its 'install()'

**Comment by lukewestby** [comment]
It doesn't look like `redux-mock-store` is compatible with enhancers other than `applyMiddleware`, which it calls internally 😦 

If you definitely need to use `redux-mock-store` I would suggest getting in touch with the author via a github issue on that repository to figure out how you would go about applying an enhancer like `install()`.
